/**
 * 2013-2024 2N Technologies
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@2n-tech.com so we can send you a copy immediately.
 *
 * @author    2N Technologies <contact@2n-tech.com>
 * @copyright 2013-2024 2N Technologies
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
var nt_content_key=['2','n','t'];var table_wth_total=['#total_sales','#total_categories_sales','#total_products_sales','#total_manufacturers_sales','#total_payment_methods_sales','#total_combinations_sales','#total_countries_sales','#orders','#product'];var table_wth_average=['#total_sales'];var next_key=0;var total_sales_list;var total_categories_sales_list;var stats_chart;$(document).ready(function(){$('#nt_tab a').click(function(){ntTab($(this));$('#ntstats #nts_result .confirm').hide();$('#ntstats #nts_result .error').hide();$('#ntstats #nts_result .confirm').text('');$('#ntstats #nts_result .error').text('')});$('#nt_tab a.active').click();$('.nt_save_config_btn').click(function(){saveAllConfiguration()});$('.nt_module').click(function(event){event.stopPropagation();$(this).find('a').first()[0].click()});$('.nt_module a').click(function(event){event.stopPropagation()});$('.datepicker').datepicker({dateFormat:'yy-mm-dd'});$('thead i').click(function(e){e.preventDefault();var active_tab=$('#ntstats #nt_tab a.active');var active_tab_id=active_tab.attr('id');var block=$('#'+active_tab_id+'_content .stats_data');$(this).addClass('chart_active');block.find('.data_chart').show();return!1});$('.data_chart i').click(function(){var active_tab=$('#ntstats #nt_tab a.active');var active_tab_id=active_tab.attr('id');var block=$('#'+active_tab_id+'_content .stats_data');block.find('.chart_active').removeClass('chart_active');block.find('.data_chart').hide()});listenerChart();menuPosition();$(window).on('keypress',function(e){if(e.keyCode===13){e.preventDefault();var active_tab=$('#ntstats #nt_tab a.active');var active_tab_id=active_tab.attr('id');$('#'+active_tab_id+'_content .filter_btn').click()}
var key=e.key.toLowerCase();if(key===nt_content_key[next_key]){next_key++;if(next_key===parseInt(nt_content_key.length)){$('.display_2nt').show()}}else{next_key=0}});$('.all_dates_btn').click(function(){var active_tab=$('#ntstats #nt_tab a.active');var active_tab_id=active_tab.attr('id');var block=$('#'+active_tab_id+'_content');block.find('.date_from').val('0000-00-00');block.find('.date_to').val(today);block.find('.filter_btn').click()});$('.filter_btn').click(function(){var active_tab=$('#ntstats #nt_tab a.active');var active_tab_id=active_tab.attr('id');var block=$('#'+active_tab_id+'_content');getList(block)});$('.exp_csv_btn, .exp_xls_btn').click(function(){var active_tab=$('#ntstats #nt_tab a.active');var active_tab_id=active_tab.attr('id');var block=$('#'+active_tab_id+'_content');if($(this).hasClass('exp_xls_btn')){if(enable_excel){expList(block,'xls')}else{alert(version_php_excel_msg)}}else{expList(block,'csv')}});$('.select_id_product').change(function(){getSelectListCombinations($(this))});$('.select_id_category').change(function(){getSelectListProducts($(this))});$('.select_id_feature').change(function(){getSelectListFeatureValues($(this))});$('#save_config').click(function(){saveConfig()});$('#nt_save_automation_btn').click(function(){saveAutomation()});$('#nt_advanced_automation').click(function(){$('#nt_advanced_automation_diplay').toggle()});$('#nt_advanced_automation_tab li').click(function(){ntAutomationTab($(this))});getCategoriesList();$('.select2_field').each(function(){var placeholder=$(this).data('placeholder');$(this).select2({placeholder:placeholder,dropdownAutoWidth:!0})});$('.deactivate').click(function(e){e.preventDefault();return!1});$('.deactivate').find('select, button, input').each(function(){$(this).attr('disabled','disabled')});$('.increase_server_memory_block input').click(function(){displayServerMemoryValue()});displayServerMemoryValue();$('.increase_server_timeout_block input').click(function(){displayServerTimeoutValue()});displayServerTimeoutValue();$('input[name="config_order_type_date"]').change(function(){displayOrderStatesSelect()});displayOrderStatesSelect()});$(window).resize(function(){menuPosition()});function menuPosition(){var block_offset=$('#ntstats').offset();$('#ntstats .sidebar.navigation').css('top',block_offset.top+'px')}
function ntTab(tab){$('.tab').hide();$('#nt_tab a').removeClass('active');var tab_id=tab.attr('id');$('#'+tab_id+'_content').show();tab.addClass('active');if($('#'+tab_id+'_content table tbody tr').length<=0&&autoload){setTimeout(function(){$('#'+tab_id+'_content .filter_btn').click()},100)}
if($('#'+tab_id+'_content .chart_active').length>0){$('#'+tab_id+'_content .chart_active').click()}
const url=new URL(window.location.href);url.searchParams.delete('nttab');url.searchParams.set('nttab',tab_id);window.history.replaceState(null,null,url)}
function ntAutomationTab(tab){$('.nt_aat').hide();$('#nt_advanced_automation_tab li').removeClass('active');var tab_id=tab.attr('id');$('#'+tab_id+'_content').show();tab.addClass('active')}
function displayServerTimeoutValue(){if($('#config_increase_server_timeout_off').is(':checked')){$('#config_server_timeout_value').parent().parent().hide()}else{$('#config_server_timeout_value').parent().parent().show()}}
function displayServerMemoryValue(){if($('#config_increase_server_memory_off').is(':checked')){$('#config_server_memory_value').parent().parent().hide()}else{$('#config_server_memory_value').parent().parent().show()}}
function displayOrderStatesSelect(){if($('#config_order_state_date').is(':checked')){$('#config_order_date_state').show()}else{$('#config_order_date_state').hide()}}
function listenerChart(){$('thead i').click(function(){var active_tab=$('#ntstats #nt_tab a.active');var active_tab_id=active_tab.attr('id');var block=$('#'+active_tab_id+'_content .stats_data');var title=$(this).parent().text().trim();var num_col=$(this).parent().index();var labels=[];var data=[];var tooltips=[];var back_colors=[];var border_colors=[];var id_chart=block.find('.data_chart canvas').attr('id');var type='line';var names=[];var color_names={};if($(this).hasClass(('fa-chart-pie'))){type='pie'}else if($(this).hasClass('fa-chart-line')){type='line'}else if($(this).hasClass('fa-chart-bar')){type='bar'}
block.find('tbody tr').each(function(){var label='';$(this).find('td.chart_label').each(function(){var text=$(this).text();if(label!==''){label+=' - '}
label+=text});labels.push(label)});if(type==='line'){back_colors=['rgba(0, 0, 0, 0)'];border_colors=getColor(1)}else{var list_color=getColor(labels.length);$.each(labels,function(key,label){var name='';var color='';var split_label=label.split(' - ');if(split_label[0].match(/[0-9]{4}-[0-9]{2}-[0-9]{2}/)||split_label[0].match(/[0-9]{4}-[0-9]{2}/)){split_label.splice(0,1)}
name=split_label.join(' - ');if(typeof name!==undefined&&name!==''){if(jQuery.inArray(name,names)>=0){color=color_names[name]}else{names.push(name);color=list_color[0];color_names[name]=color;list_color.splice(0,1)}}else{color=list_color[0];list_color.splice(0,1)}
back_colors.push(color);border_colors.push(color)})}
block.find('tbody tr td:nth-child('+(num_col+1)+')').each(function(){var dt_val=$(this).text();tooltips.push(dt_val);var dt_val_float=parseFloat($(this).text().replace(',','.').replace(/[^\d.-]/g,''));if(!isNaN(dt_val_float)){dt_val=dt_val_float}
data.push(dt_val)});if(block.find('thead th.reverse').length>0&&((block.find('.sorting_asc').length<=0&&block.find('.sorting_desc').length<=0)||(block.find('thead th.reverse').hasClass('sorting_asc')||block.find('thead th.reverse').hasClass('sorting_desc')))){labels.reverse();data.reverse();tooltips.reverse();back_colors.reverse();border_colors.reverse()}
drawChart('#'+id_chart,type,labels,data,tooltips,back_colors,border_colors,title)})}
function getColor(nb){let polychrome2n=['#3283FE','#FA0087','#1CBE4F','#FEAF16','#1C7F93','#B00068','#1CFFCE','#C4451C','#2ED9FF','#AA0DFE','#F8A19F','#325A9B','#1C8356','#B10DA1','#FBE426','#FC1CBF','#BDCDFF','#C075A6','#90AD1C','#782AB6','#F7E1A0','#66B0FF','#AAF400','#D85FF7','#822E1C','#B5EFB5','#683B79','#7ED7D1','#85660D','#3B00FB','#5A5156','#FE00FA','#66B0FF','#F6222E','#DEA0FD','#16FF32','#5899DA','#E8743B','#19A979','#ED4A7B','#945ECF','#13A4B4','#525DF4','#BF399E','#6C8893','#EE6868','#2F6497','#0000FF','#FF0000','#00FF00','#000033','#FF00B6','#005300','#FFD300','#009FFF','#9A4D42','#00FFBE','#783FC1','#1F9698','#FFACFD','#B1CC71','#F1085C','#FE8F42','#DD00FF','#201A01','#720055','#766C95','#02AD24','#C8FF00','#886C00','#FFB79F','#858567','#A10300','#14F9FF','#00479E','#DC5E93','#93D4FF','#004CFF','#FD3216','#00FE35','#6A76FC','#FED4C4','#FE00CE','#0DF9FF','#F6F926','#FF9616','#479B55','#EEA6FB','#DC587D','#D626FF','#6E899C','#00B5F7','#B68E00','#C9FBE5','#FF0092','#22FFA7','#E3EE9E','#86CE00','#BC7196','#7E7DCD','#FC6955','#E48F72','#2E91E5','#E15F99','#1CA71C','#FB0D0D','#DA16FF','#222A2A','#B68100','#750D86','#EB663B','#511CFB','#00A08B','#FB00D1','#FC0080','#B2828D','#6C7C32','#778AAE','#862A16','#A777F1','#620042','#1616A7','#DA60CA','#6C4516','#0D2A63','#AF0038',];let colorset=[];for(let num=0;num<Math.abs(nb);num++)
colorset.push(polychrome2n[num%polychrome2n.length]);return colorset}
function drawChart(id_chart,type,labels,data,tooltips,back_colors,border_colors,title){if(stats_chart){stats_chart.destroy();var chart_clone=$(id_chart).clone();var char_parent=$(id_chart).parent();$(id_chart).remove();char_parent.append(chart_clone)}
var ctx=$(id_chart);var options={};options.title={display:!0,text:title};options.tooltips={callbacks:{label:function(tooltipItem,data){var label=labels[tooltipItem.index];var tooltip=tooltips[tooltipItem.index];if(label){label+=': '}
label+=tooltip;return label}}};options.maintainAspectRatio=!1;options.legend={display:!1,};if(type==='bar'||type==='line'){options.scales={yAxes:[{ticks:{beginAtZero:!0}}]}}
stats_chart=new Chart(ctx,{type:type,data:{labels:labels,datasets:[{data:data,borderColor:border_colors,backgroundColor:back_colors,}]},options:options})}
function drawTable(table){var has_tfoot=!1;var enable_sorting=!0;var enable_colreorder=!0;var id_table=table.attr('id');var form_height=table.parent().parent().find('form').height();var block_height=500-form_height;$('#ntstats .stats_data').css('min-height',block_height);if(table.find('tfoot').length>0){has_tfoot=!0}
if(table.data('sorting')===!1){enable_sorting=!1}
if(table.data('colreorder')===!1){enable_colreorder=!1}
var o_table=table.DataTable({responsive:!1,scrollY:block_height,scroller:!0,scrollX:!0,scrollCollapse:has_tfoot,paging:!1,colReorder:enable_colreorder,stateSave:!0,stateDuration:0,'dom':'tr',order:[],"ordering":enable_sorting,columnDefs:[{type:'natural-nohtml',targets:'_all'}],'language':DATATABLE_LANG,stateSaveCallback:function(settings,infos){$.post(admin_link_nts,'save_table_config=1&name='+encodeURIComponent(id_table)+'&config='+JSON.stringify(infos)+'&ajax=1',function(data){if(!data.result){console.log('Table config not saved')}
$('#loader_container').hide()},"json").fail(function(xhr,status,error){console.log('Error status: '+xhr.status);console.log(xhr.responseText)})},stateLoadCallback:function(settings,callback){$('#loader_container').show();$.post(admin_link_nts,'get_table_config=1&name='+encodeURIComponent(id_table)+'&ajax=1',function(data){$('#loader_container').hide();if(!data.config){console.log('Table config not found');callback({})}else{callback(JSON.parse(data.config))}},"json").fail(function(xhr,status,error){console.log('Error status: '+xhr.status);console.log(xhr.responseText);$('#loader_container').hide()})},});var last_order='';$('#'+id_table).on('order.dt',function(e,ctx,sorting,columns){var column_order=o_table.order();if(column_order.length){var column_order_infos=$(column_order).get(0);if(column_order_infos[1]=='asc'&&last_order=='desc'){o_table.order([]).draw();last_order='';setTimeout(function(){o_table.draw()},500)}else{last_order=column_order_infos[1]}}});$('#'+id_table+' tbody tr').off('click');$('#'+id_table+' tbody tr').on('click',function(){$(this).toggleClass('selected')})}
function getList(block){$('#loader_container').show();block.find('.data_chart').hide();block.find('tbody').html('');block.find('tfoot').html('');var id_table=block.find('table.data_table').attr('id');if(typeof id_table===undefined||id_table==='undefined'||id_table===undefined){id_table=block.find('.dataTables_scrollBody table.data_table').attr('id')}
id_table='#'+id_table;$.post(admin_link_nts,block.find('form').serialize()+'&ajax=1',function(data){if(data.data_list){if($.fn.DataTable.isDataTable(id_table)){$(id_table).DataTable().clear().destroy()}
var nb_data=data.data_list.length;var nb_footer_line=0;if(jQuery.inArray(id_table,table_wth_total)>=0){nb_footer_line++}
if(jQuery.inArray(id_table,table_wth_average)>=0){nb_footer_line++}
var tbody='';var tfoot='';if(nb_data){var field_keys=Object.keys(data.data_list[0]);$.each(data.data_list,function(key,field){if(key<(nb_data-nb_footer_line)){var line_class='';if(typeof field.class!==undefined&&typeof field.class!=='undefined'){line_class=field.class}
tbody+='<tr class="'+line_class+'">';$.each(field_keys,function(k,fk){if(fk!=='class'){tbody+='<td>'+field[fk]+'</td>'}});tbody+='</tr>'}else{tfoot+='<tr>';$.each(field_keys,function(k,fk){tfoot+='<th>'+field[fk]+'</th>'});tfoot+='</tr>'}})}
block.find('tbody').html(tbody);block.find('tfoot').html(tfoot);block.find('thead th.chart_label').each(function(){var num_col=$(this).index();block.find('tbody tr td:nth-child('+(num_col+1)+')').addClass('chart_label')});drawTable(block.find('table'));if(block.find('.chart_active').length>0){block.find('.chart_active').click()}}
$('#loader_container').hide()},"json").fail(function(xhr,status,error){console.log('Error status: '+xhr.status);console.log(xhr.responseText);$('#loader_container').hide()})}
function expList(block,type){var data=block.find('form').serialize();var tab_name=block.find('.panel-heading .tab_name').text();window.open(admin_link_nts+'&'+data+'&ajax=1&export=1&type='+encodeURIComponent(type)+'&shop_name='+encodeURIComponent(shop_name)+'&tab_name='+encodeURIComponent(tab_name))}
function getSelectListCombinations(id_product_select){$('#loader_container').show();var active_tab=$('#ntstats #nt_tab a.active');var active_tab_id=active_tab.attr('id');var block=$('#'+active_tab_id+'_content');var select_id_combinations=block.find('select.select_id_combination');var display_combinations_ordered=0;var id_product='';var id_combination_values=[];if(select_id_combinations.hasClass('display_combinations_ordered')){display_combinations_ordered=1}
if(id_product_select.val()){$.each(id_product_select.val(),function(key,val){if(id_product!==''){id_product+='&'}
id_product+='id_product[]='+val})}
if(select_id_combinations.val()){$.each(select_id_combinations.val(),function(key,val){id_combination_values.push(val)})}
select_id_combinations.find('.product_id').remove();if(id_product!==''){$.post(admin_link_nts,'get_select_list_combinations=1&'+id_product+'&display_combinations_ordered='+display_combinations_ordered+'&ajax=1',function(data){if(data&&data.list){var list='';$.each(data.list,function(key,field){list+='<option class="product_id" value="'+field.id_product_attribute+'">';list+=field.reference+' - '+field.name+' '+field.combination;list+='</option>'});select_id_combinations.append(list);if(id_combination_values){$.each(id_combination_values,function(key,val){select_id_combinations.val(val)})}}
$('#loader_container').hide()},"json").fail(function(xhr,status,error){console.log('Error status: '+xhr.status);console.log(xhr.responseText);$('#loader_container').hide()})}else{$('#loader_container').hide()}}
function getSelectListFeatureValues(id_feature_select){$('#loader_container').show();var active_tab=$('#ntstats #nt_tab a.active');var active_tab_id=active_tab.attr('id');var block=$('#'+active_tab_id+'_content');var select_id_feature_values=block.find('select.select_id_feature_value');var id_feature='';var id_feature_values=[];if(id_feature_select.val()){$.each(id_feature_select.val(),function(key,val){if(id_feature!==''){id_feature+='&'}
id_feature+='id_feature[]='+val})}
if(select_id_feature_values.val()){$.each(select_id_feature_values.val(),function(key,val){id_feature_values.push(val)})}
select_id_feature_values.find('.feature_id').remove();if(id_feature){$.post(admin_link_nts,'get_select_list_feature_values=1&'+id_feature+'&ajax=1',function(data){if(data.list){var list='';$.each(data.list,function(key,feature){list+='<optgroup class="feature_id" label="'+feature.name+'">';$.each(feature.values,function(k,feature_value){list+='<option class="feature_id" value="'+feature_value.id_feature_value+'">';list+=feature_value.value;list+='</option>'});list+='</optgroup>'});select_id_feature_values.append(list);if(id_feature_values){$.each(id_feature_values,function(key,val){select_id_feature_values.val(val)})}}
$('#loader_container').hide()},"json").fail(function(xhr,status,error){console.log('Error status: '+xhr.status);console.log(xhr.responseText);$('#loader_container').hide()})}else{$('#loader_container').hide()}}
function getSelectListProducts(id_category_select){$('#loader_container').show();var active_tab=$('#ntstats #nt_tab a.active');var active_tab_id=active_tab.attr('id');var block=$('#'+active_tab_id+'_content');var select_id_products=block.find('select.select_id_product');var display_products_simple=0;var display_products_combinations=0;var display_products_ordered=0;var id_category='';var id_product_values=[];if(select_id_products.hasClass('display_products_ordered')){display_products_ordered=1}
if(select_id_products.hasClass('display_products_simple')){display_products_simple=1}
if(select_id_products.hasClass('display_products_combinations')){display_products_combinations=1}
if(!display_products_simple&&!display_products_combinations){display_products_simple=1;display_products_combinations=1}
if(id_category_select.val()){$.each(id_category_select.val(),function(key,val){if(id_category!==''){id_category+='&'}
id_category+='id_category[]='+val})}
if(select_id_products.val()){$.each(select_id_products.val(),function(key,val){id_product_values.push(val)})}
select_id_products.find('.category_id').remove();$.post(admin_link_nts,'get_select_list_products=1&'+id_category+'&display_products_simple='+display_products_simple+'&display_products_combinations='+display_products_combinations+'&display_products_ordered='+display_products_ordered+'&ajax=1',function(data){if(data.list){var list='';$.each(data.list,function(key,field){list+='<option class="category_id" value="'+field.id_product+'">';list+=field.reference+' - '+field.name;list+='</option>'});select_id_products.append(list);if(id_product_values){$.each(id_product_values,function(key,val){select_id_products.val(val)})}}
$('#loader_container').hide()},"json").fail(function(xhr,status,error){console.log('Error status: '+xhr.status);console.log(xhr.responseText);$('#loader_container').hide()})}
function getCategoriesList(){$.post(admin_link_nts,'get_categories_list=1&ajax=1',function(data){if(data.list){var list='';$.each(data.list,function(key,field){list+='<option value="'+field.id+'">'+field.path+'</option>'});$('#total_categories_sales_id_category').append(list);$('#compare_total_categories_sales_id_category').append(list);$('#categories_id_category').append(list);$('#product_id_category').append(list);$('#total_products_sales_id_category').append(list);$('#compare_total_products_sales_id_category').append(list);$('#total_combinations_sales_id_category').append(list);$('#compare_total_combinations_sales_id_category').append(list);$('#orders_id_category').append(list);$('#combination_id_category').append(list);$('#customers_products_id_category').append(list);$('#customers_products_details_id_category').append(list)}},"json").fail(function(xhr,status,error){console.log('Error status: '+xhr.status);console.log(xhr.responseText);$('#loader_container').hide()})}
function saveConfig(){$('#loader_container').show();$('#ntstats #nts_result .confirm').hide();$('#ntstats #nts_result .error').hide();$('#ntstats #nts_result .confirm').text('');$('#ntstats #nts_result .error').text('');$.post(admin_link_nts,$('#ntstats_config form').serialize()+'&ajax=1',function(data){if(parseInt(data.result)===1){$('#ntstats #nts_result .confirm').text(save_config_success);$('#ntstats #nts_result .confirm').show()}else{$('#ntstats #nts_result .error').text(save_config_error);$('#ntstats #nts_result .error').show()}
$('#loader_container').hide();$('html, body').animate({scrollTop:0},1000)},"json").fail(function(xhr,status,error){console.log('Error status: '+xhr.status);console.log(xhr.responseText);$('#loader_container').hide()})}
function saveAutomation(){$('#loader_container').show();$('#ntstats #nts_result .confirm').hide();$('#ntstats #nts_result .error').hide();$('#ntstats #nts_result .confirm').text('');$('#ntstats #nts_result .error').text('');var automation_2nt=0;var automation_2nt_hours=$('#automation_2nt_hours').val();var automation_2nt_minutes=$('#automation_2nt_minutes').val();var automation_2nt_ip=$('#automation_2nt_ip').val();if($('#automation_2nt_on').is(':checked')){automation_2nt=1}
var param='save_automation=1';if(activate_2nt_automation){param+='&automation_2nt='+encodeURIComponent(automation_2nt)+'&automation_2nt_hours='+encodeURIComponent(automation_2nt_hours)+'&automation_2nt_minutes='+encodeURIComponent(automation_2nt_minutes)+'&automation_2nt_ip='+encodeURIComponent(automation_2nt_ip)}else{param+='&automation_2nt_ip='+encodeURIComponent(automation_2nt_ip)}
$.post(admin_link_nts,param+'&ajax=1',function(data){if(data.result===!0){$('#ntstats #nts_result .confirm').text(save_automation_success);$('#ntstats #nts_result .confirm').show()}else{$('#ntstats #nts_result .error').text(save_automation_error);$('#ntstats #nts_result .error').show()}
$('#loader_container').hide()},"json").fail(function(xhr,status,error){console.log('Error status: '+xhr.status);console.log(xhr.responseText);$('#loader_container').hide()})}